//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioVisualesAPEC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipos()
        {
            this.Prestamos = new HashSet<Prestamos>();
        }
    
        public int IdEquipo { get; set; }
        public string Descripcion { get; set; }
        public string Serial { get; set; }
        public string ServiceTag { get; set; }
        public int IdTipoEquipo { get; set; }
        public int IdMarca { get; set; }
        public int IdModelo { get; set; }
        public int IdTecnologia { get; set; }
        public string Estado { get; set; }
    
        public virtual Marcas Marcas { get; set; }
        public virtual Modelos Modelos { get; set; }
        public virtual Tecnologias Tecnologias { get; set; }
        public virtual TiposEquipos TiposEquipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamos> Prestamos { get; set; }
    }
}
